version: '3'
services:
  mongo-database:
    build: "../mongo-service"
    hostname: mongodb-server
    ports:
      - "27017:27017"
    networks:
      - vsu-microservices
    container_name: "mongodb-server"

  flats-microservice:
    build: "../flats-microservice/."
    hostname: "flats-server"
    container_name: "flats-server"
    environment:
      - DB_SERVERS=mongodb-server:27017
    networks:
      - vsu-microservices
    depends_on:
      - "mongo-database"
    ports:
      - "3000:3000"

  auth-microservice:
    build: "../auth-microservice/."
    hostname: "auth-server"
    container_name: "auth-server"
    environment:
      - DB_SERVERS=mongodb-server:27017
    networks:
      - vsu-microservices
    depends_on:
      - "mongo-database"
    ports:
      - "3001:3000"

  measurements-microservice:
    build: "../measurements-microservice/."
    hostname: "measurements-microservice"
    container_name: "measurements-microservice"
    environment:
      - DB_SERVERS=mongodb-server:27017
    networks:
      - vsu-microservices
    depends_on:
      - "mongo-database"
    ports:
      - "3002:3000"

  receipts-microservice:
    build: "../receipts-microservice/."
    hostname: "receipts-microservice"
    container_name: "receipts-microservice"
    environment:
      - DB_SERVERS=mongodb-server:27017
      - AUTH_HOST=auth-server
      - AUTH_PORT=3000
    networks:
      - vsu-microservices
    depends_on:
      - "mongo-database"
      - "auth-microservice"
    ports:
      - "3003:3000"

networks:
  vsu-microservices:
    driver: bridge